version: '3.0'

services:
  db:
    image: couchdb:2.2
    volumes:
      - ${DATABASE_DIRECTORY}:/opt/couchdb/data
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    restart: unless-stopped

  cozy:
    image: vsellier/easy-cozy:${COZY_STACK_VERSION:-latest}
    environment:
      COZY_ADMIN_PASSWORD: ${COZY_ADMIN_PASSWORD:-changeme}
      COZY_TLD: ${COZY_TLD}
    volumes:
      - ${STORAGE_DIRECTORY}:/usr/local/cozy-stack/storage
    labels:
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=HostRegexp:${COZY_TLD},{subdomain:.*}.${COZY_TLD}"
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=http,https"
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    restart: unless-stopped
  
  front:
    image: traefik:1.7.12
    restart: on-failure
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.toml:/traefik.toml
      - ${ACME_DIRECTORY}:/credentials
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    restart: unless-stopped
    command: [ "--acme.email=${EMAIL:-contact@mydomain.tld}"]
