apiVersion: v1
kind: PersistentVolume
metadata:
  name: easy-cozy-db-volume
  labels:
    app: easy-cozy
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /srv/cozy/db
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: easy-cozy
          operator: Exists
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: easy-cozy-file-volume
  labels:
    app: easy-cozy
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /srv/cozy/storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: easy-cozy
          operator: Exists
